CREATE DATABASE IF NOT EXISTS waph_team;

DROP USER IF EXISTS 'WAPHTEAM1'@'localhost';

CREATE USER 'WAPHTEAM1'@'localhost' IDENTIFIED BY 'teamproject';

GRANT ALL PRIVILEGES ON waph_team.* TO 'WAPHTEAM1'@'localhost';

FLUSH PRIVILEGES;
